version: '3'

services:
  frontend:
    build: ./client
    restart: always
    ports:
      - '3000:3000'
  api:
    build: ./mern-chat-backend
    restart: always
    ports:
      - '5555:5000'
    depends_on:
      - mysql
